update Dockerfile

diff --git a/newDockerfile b/newDockerfile
--- a/newDockerfile
+++ b/newDockerfile
@@ -133,48 +133,53 @@ ARG ADDITIONAL_DEVELOPMENT_PACKAGES="\
     tmux \
     screen \
     rsync \
-    # qemu-kvm \
-    # virtinst \
-    # bridge-utils \
-    # libvirt-daemon \
-    # libvirt-clients \
-    # libvirt-daemon-system \
     "
 
-WORKDIR /code
-# Ruby gems
-COPY Gemfile .
-
-# Combine multiple RUN commands into one
+# Check package availability
 RUN apt-get update && \
     apt-get upgrade -y && \
     echo "$BASEMENT_PACKAGES $ADDITIONAL_DEVELOPMENT_PACKAGES" | \
-    xargs -n 1 bash -c 'apt-cache show $0 >/dev/null 2>&1 || { echo "Package $0 not found"; exit 1; }' && \
-    apt-get update && \
-    apt-get install --no-install-recommends -y $BASEMENT_PACKAGES $ADDITIONAL_DEVELOPMENT_PACKAGES && \
-    apt-get clean -q -y && \
-    apt-get autoremove -q -y && \
-    apt-get autoclean -q -y && \
-    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
-    ## Rust
-    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
-    ## arm-gnu-toolchain
-    if [ "$(uname -m)" = "aarch64" ]; then wget ${GCC_AARCH64}; else wget ${GCC_X86_64}; fi && \
-    mkdir -p ./arm-gnu-toolchain && \
-    tar -xJvf arm-gnu-toolchain-13.3* -C ./arm-gnu-toolchain && \
+    xargs -n 1 bash -c 'apt-cache show $0 >/dev/null 2>&1 || { echo "Package $0 not found"; exit 1; }'
+
+# Update apt source and install necessary packages
+RUN apt-get update \
+    && apt-get install --no-install-recommends -y $BASEMENT_PACKAGES $ADDITIONAL_DEVELOPMENT_PACKAGES \
+    && apt-get clean -q -y \
+    && apt-get autoremove -q -y \
+    && apt-get autoclean -q -y \
+    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
+
+WORKDIR /code
+
+# Ruby
+COPY Gemfile .
+# GDB
+COPY .gdbinit /root/.gdbinit
+COPY auto /root/.gdbinit.d/auto
+
+RUN locale-gen en_US.UTF-8; \
+    # rustup
+    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y; \
+    # arm-gnu-toolchain
+    if [ "$(uname -m)" = "aarch64" ]; then wget ${GCC_AARCH64}; else wget ${GCC_X86_64}; fi; \
+    tar -xJvf arm-gnu-toolchain-13.3*.tar.xz && \
     rm -rf arm-gnu-toolchain-13.3*.tar.xz && \
-    mv ./arm-gnu-toolchain ${OPT_APP}/ && \
-    ## Ruby
+    mv ./arm-gnu-toolchain-13.3* ${OPT_APP}/ ; \
+    cd ~ ; \
+    # Rubygems
     gem install bundler && \
     bundle config set --local without 'development' && \
-    bundle install --retry 3 && \
-    ## QEMU
-    git clone --recurse-submodules --depth 1 -b stable-9.1 https://github.com/qemu/qemu.git && \
+    bundle install --retry 3
+
+## Qemu .gitmodules 中的 https://gitlab.com/ 无法访问
+RUN git clone --recurse-submodules --depth 1 -b stable-9.1 https://github.com/qemu/qemu.git && \
     cd qemu && \
     ./configure \
     --prefix=${OPT_APP}/qemu \
+    --target-list=aarch64-softmmu,aarch64-linux-user,x86_64-softmmu,x86_64-linux-user,riscv64-softmmu,riscv64-linux-user,loongarch64-softmmu,loongarch64-linux-user \
     --enable-modules \
     --enable-tcg-interpreter \
+    --enable-debug \
     --enable-debug-tcg       \
     --enable-slirp \
     --enable-linux-user \
@@ -192,11 +197,12 @@ RUN apt-get update && \
     make -j$(nproc) && \
     make install && \
     ldconfig && \
-    make clean && \
-    cd ..; \
-    ## OpenOCD
-    git clone --recurse-submodules --depth 1 -b master https://github.com/openocd-org/openocd.git && \
+    make clean
+
+# openocd
+RUN git clone --recurse-submodules --depth 1 -b master https://github.com/openocd-org/openocd.git && \
     cd openocd && \
+    ##git checkout tags/v0.12.0 && \
     ./bootstrap && \
     ./configure \
     --prefix=${OPT_APP}/openocd \
@@ -207,10 +213,10 @@ RUN apt-get update && \
     make -j$(nproc) && \
     make install && \
     ldconfig && \
-    make clean && \
-    cd ..; \
-    ## ffmpeg
-    git clone --recurse-submodules --depth 1 -b release/7.0 https://github.com/FFmpeg/FFmpeg.git && \
+    make clean
+
+# ffmpeg
+RUN git clone --recurse-submodules --depth 1 -b release/7.0 https://github.com/FFmpeg/FFmpeg.git && \
     cd FFmpeg && \
     ./configure \
     --prefix=${OPT_APP}/ffmpeg \
@@ -231,10 +237,10 @@ RUN apt-get update && \
     make -j$(nproc) && \
     make install && \
     ldconfig && \
-    make clean && \
-    cd ..; \
-    ## OpenCV
-    git clone --recurse-submodules --depth 1 -b 4.x https://github.com/opencv/opencv.git && \
+    make clean
+
+# opencv
+RUN git clone --recurse-submodules --depth 1 -b 4.x https://github.com/opencv/opencv.git && \
     git clone --recurse-submodules --depth 1 -b 4.x https://github.com/opencv/opencv_contrib.git && \
     cd opencv && \
     mkdir build && cd build && \
@@ -255,24 +261,20 @@ RUN apt-get update && \
     make -j$(nproc) && \
     make install && \
     ldconfig && \
-    make clean && \
-    cd ../..; \
-    ## timezone
-    locale-gen en_US.UTF-8 && \
-    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
-    echo $TZ > /etc/timezone && \
-    localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8 && \
-    cat ~/.zshrc | sed 's/lucid wait//g;s/zinit light/zinit load/g;s/#.*$//g;/^zinit ice *$/d' > /tmp/zshrc && \
-    sed -i '/^$/d' /tmp/zshrc && \
-    zsh -c "TERM=xterm source /tmp/zshrc; nvim -c 'q'; rm -rf /tmp/*; exit 0" && \
-    chsh -s /bin/zsh; \
-    # GDB
-    wget -P ~ git.io/.gdbinit; \
-    # Cleanup
-    apt-get purge -y --auto-remove $BASEMENT_PACKAGES $ADDITIONAL_DEVELOPMENT_PACKAGES; \
-    apt-get autoremove -q -y;                 \
-    apt-get clean -q -y;                      \
-    rm -rf /var/lib/apt/lists/*
+    make clean
 
-# GDB
-COPY auto /root/.gdbinit.d/auto
+ENV PATH="$HOME/.cargo/bin:${OPT_APP}/openocd/bin:${OPT_APP}/ffmpeg/bin:${OPT_APP}/opencv/bin:$PATH"
+ENV LD_LIBRARY_PATH="${OPT_APP}/openocd/lib:${OPT_APP}/ffmpeg/lib:${OPT_APP}/opencv/lib:$LD_LIBRARY_PATH"
+
+# Timezone and locale
+RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
+    && echo $TZ > /etc/timezone \
+    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
+
+# Initialize zinit and nvim plugins
+RUN cat ~/.zshrc | sed 's/lucid wait//g;s/zinit light/zinit load/g;s/#.*$//g;/^zinit ice *$/d' > /tmp/zshrc \
+    && sed -i '/^$/d' /tmp/zshrc \
+    && zsh -c "TERM=xterm source /tmp/zshrc; nvim -c 'q'; rm -rf /tmp/*; exit 0"
+
+RUN chsh -s /bin/zsh
+CMD ["/bin/zsh"]
